# fly.toml app configuration file generated for ustom on 2023-10-25T16:59:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ustom"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
